# Generated by Django 2.2 on 2019-08-24 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.Department'),
        ),
    ]
