# Generated by Django 2.2.13 on 2023-04-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0006_auto_20230122_1221'),
        ('students', '0002_auto_20190824_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_no', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.Department')),
            ],
        ),
    ]
