# Generated by Django 2.2 on 2019-09-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0003_auto_20190824_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='content',
        ),
        migrations.AddField(
            model_name='request',
            name='departments',
            field=models.ManyToManyField(to='clearance.Department'),
        ),
    ]
