# Generated by Django 2.2.13 on 2023-01-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0004_auto_20190904_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Cleared'), (2, 'Declined')], default=0),
        ),
    ]
